name: Withers
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6198294784408063
title: Josh Withers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1923746-45
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6caba'
    - '#151f14'
    - '#fff9f9'
    - '#8d7d63'
    - '#4aa5cf'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
